version: '3.5'
services:
  quasar:
    container_name: quasar
    build:
      context: .
      target: 'develop-stage'
    ports:
      - '9000:9000'
    volumes:
      - '.:/app'
    command: /bin/sh -c "npm install && quasar dev"
